[project]
name = "web_fillers"
version = "3.0.0"
description = "Fillers for filling assignments in the seek portal and replit"
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE.txt"}

authors = [
  {name = "Livin Nector", email = "livin@study.iitm.ac.in" }
]

dependencies = [
  "selenium","markdown-to-json","pyyaml","bs4"
]

[project.optional-dependencies]

[project.urls]
[project.scripts]
proq-template = "seek_filler.proq_gen:main"
proq-create = "seek_filler.proq_create:main"
proq2json = "seek_filler.proq_to_json:main"
proq-evaluate = "seek_filler.proq_evaluate:main"
[tool.setuptools]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"